### PR TITLE
Few fixes for minor issues

### LINKED ISSUE #98: List: filtering by year fails on last digit
As originally reported by @schmelling in OpenKnowledgeMaps/project-website#17:

"Hi this is only a small reminder.

We just tried out open knowledge maps at opencon berlin and think we found a small bug.

After the literatur search we wanted to filter by year through the feature tabs on the right and it returned 0 papers fast typing '2016' or '2015'. However '201' worked for showing the last decade.

Filtering by options in the beginning works fine.

Thanks for the great tool.
Cheers,
Nic"

### LINKED ISSUE #99: local_files: filtering has unexpected results
When a paper is selected in the local_files example, and the user enters a search term in the box, all the papers from this bubble matching the search term are shown in the list. The correct behaviour would be to show just the enlarged paper. This is also the way it works in the search_repos example. May be related to #28.

### PR DESCRIPTION
**Pull request by Bubblbu**
+ Fixes #99 (filtering of list while paper selected)
+ Fixes #98 (filtering by year)
+ Some mysterious behaviour for #28. See issue thread

### CODE REVIEW

File: vis/js/mediator.js [hunk 1]
```diff
@@ -405,6 +405,7 @@ MyMediator.prototype = {
         mediator.current_bubble.current = "hoverbig";
         mediator.manager.call('papers', 'mouseoverpaper', []);
         mediator.manager.call('list', 'enlargeListItem', [d]);
+        d.paper_selected = true;
         mediator.current_enlarged_paper = d;
```
Comment (rbachleitner) [inline vis/js/mediator.js]: This should probably go to `list.enlargeListItem` in the end.

Comment (Bubblbu) [inline vis/js/mediator.js]: Agree! :+1:

**Comment by pkraker** [comment]
Nice work!
